version: '3.8'

services:
  sfera-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: sfera-api-prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    networks:
      - sfera-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  sfera-network:
    driver: bridge